### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by MirageJiang** [MirageJiang/Web#1]
1. What choices do we have for framework?
2. Pros and Cons for each choice?
3. Which one do you think we should use? Why?

**Comment by mochen0505** [comment]
1. Laravel , that is all I know, the best full stack framework in the world
2. 3. check out the atteched picture
![_20160301191113](https://cloud.githubusercontent.com/assets/10392757/13446419/6245c79c-dfe1-11e5-80b8-c866bb20b6f8.jpg)
